export const sentences = [
`Toddlers feeding raccoons surprised even the seasoned park ranger.`,
`Peanut butter and jelly caused the elderly lady to think about her past.`,
`The doll spun around in circles in hopes of coming alive.`,
`Fluffy pink unicorns are a popular status symbol among macho men.`,
`Peanuts don't grow on trees, but cashews do.`,
`He didn't understand why the bird wanted to ride the bicycle.`,
`I am my aunt's sister's daughter.`,
`As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.`,
`Iron pyrite is the most foolish of all minerals.`,
`That was how he came to win $1 million.`,
`Each person who knows you has a different perception of who you are.`,
`He realized there had been several deaths on this road, but his concern rose when he saw the exact number.`,
`It had been sixteen days since the zombies first attacked.`,
`The mysterious diary records the voice.`,
`Blue sounded too cold at the time and yet it seemed to work for gin.`,
`After fighting off the alligator, Brian still had to face the anaconda.`,
`He invested some skill points in Charisma and Strength.`,
`It was at that moment that he learned there are certain parts of the body that you should never Nair.`,
`We need to rent a room for our party.`,
`We have never been to Asia, nor have we visited Africa.`,
`The hand sanitizer was actually clear glue.`,
`She did her best to help him.`,
`He always wore his sunglasses at night.`,
`Lets all be unique together until we realise we are all the same.`,
`Art doesn't have to be intentional.`,
`They looked up at the sky and saw a million stars.`,
`I am happy to take your donation; any amount will be greatly appreciated.`,
`Some bathing suits just shouldn’t be worn by some people.`,
`Three years later, the coffin was still full of Jello.`,
`If you don't like toenails, you probably shouldn't look at your feet.`,
`They got there early, and they got really good seats.`,
`She moved forward only because she trusted that the ending she now was going through must be followed by a new beginning.`,
`A song can make or ruin a person’s day if they let it get to them.`,
`Everyone was busy, so I went to the movie alone.`,
`The waves were crashing on the shore; it was a lovely sight.`,
`Charles ate the french fries knowing they would be his last meal.`,
`He was 100% into fasting with her until he understood that meant he couldn't eat.`,
`There was no telling what thoughts would come from the machine.`,
`It's not often you find a soggy banana on the street.`,
`Mothers spend months of their lives waiting on their children.`,
`All you need to do is pick up the pen and begin.`,
`She had a habit of taking showers in lemonade.`,
`The tears of a clown make my lipstick run, but my shower cap is still intact.`,
`She used her own hair in the soup to give it more flavor.`,
`He loved eating his bananas in hot dog buns.`,
`If any cop asks you where you were, just say you were visiting Kansas.`,
`Choosing to do nothing is still a choice, after all.`,
`She wore green lipstick like a fashion icon.`,
`You have every right to be angry, but that doesn't give you the right to be mean.`,
`She was the type of girl who wanted to live in a pink house.`,
];
